# Generated by Django 3.2.21 on 2023-09-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_tables',
            field=models.IntegerField(default=25),
        ),
    ]
