# Generated by Django 3.2.21 on 2023-09-19 18:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, default='none', max_length=255, null=True, verbose_name='image'),
        ),
    ]
